host = "127.0.0.1"
port = 7379
storage_path = "data"
engine = "sled"
sync_interval_seconds = 60

[replication]
enabled = false
mqtt_broker = "localhost"
mqtt_port = 1883
topic_prefix = "merkle_kv"
client_id = "node1"
[network]
bind_address = "127.0.0.1"
bind_port = 7379

[mqtt]
broker_address = "tcp://test.mosquitto.org:1883"
topic_prefix = "quickstart-merkle-kv"